name: Generate Python Client

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      openapi_url:
        description: "URL to the OpenAPI specification file"
        required: true
        default: "https://docs.repliers.io/openapi/623b8d72c3688c076e0b802a"
      tag_name:
        description: "Tag name for the release (e.g., v1.0.0)"
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install openapi-python-client
          
      - name: Generate Python client
        run: |
          openapi-python-client generate --url ${{ github.event.inputs.openapi_url }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }} # Use the tag_name input
          release_name: "Release ${{ github.event.inputs.tag_name }}" # Customize as needed
          body: |
            Generated Python client from OpenAPI specification.
          draft: false
          prerelease: false
